[package]
name = "cw20-ics20-msg"
version = "0.0.1"
authors = ["Oraichain Labs"]
edition = "2021"
description = "Definition and types for the cw20-ics20-msg interface"
license = "Apache-2.0"
repository = "https://github.com/Oraichain/ibc-bridge-wasm"
homepage = "https://orai.io"

[dependencies]
cosmwasm-schema = "1.1.9"
cosmwasm-std = { version = "1.1.9", default-features = false }
cw-storage-plus = "1.0.1"
cw20 = "1.0.1"

